# Generated by Django 3.2.12 on 2022-06-14 09:00

import admins.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(help_text='yyyy-mm-dd')),
                ('mobileNo', models.IntegerField(validators=[admins.models.mobileNoValidate])),
                ('aadharNo', models.IntegerField(max_length=12, unique=True)),
                ('rationNo', models.CharField(max_length=10, unique=True)),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('wardNo', models.IntegerField()),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Volunteers.volunteerregistrationmodel')),
            ],
        ),
    ]
