# Generated by Django 3.2.12 on 2022-06-14 09:21

import admins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='mobileNo',
            field=models.IntegerField(max_length=10, validators=[admins.models.mobileNoValidate]),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='rationNo',
            field=models.CharField(max_length=10),
        ),
    ]
